apiVersion: v1
kind: Service
metadata:
  name: roadsidehelp-service
  namespace: roadsidehelp
spec:
  type: NodePort
  selector:
    app: roadsidehelp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
